SELECT 
   DATA_VENDA AS PERIODO, VENDA AS VENDA_TOTAL, ID_VENDA AS VENDAS_REAL,
    CAST(SUM(VENDA) 
      OVER (    
       ORDER BY PERIODO 
       ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    )AS FLOAT) AS VENDA_ACUMULADA
FROM {{ ref('stg_venda') }} 





