SELECT 
   DATA_VENDA AS PERIODO, 
    CAST(SUM(VENDA) 
      OVER (
       ORDER BY PERIODO
       ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    )AS FLOAT) AS VENDA_ACUMULADA
FROM {{ ref('stg_venda') }} 






